# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


movies = [
[
    {
        "rank": "1",
        "rank_up_down": "0",
        "title": "The Gray Man",
        "full_title": "The Gray Man (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOWY4MmFiY2QtMzE1YS00NTg1LWIwOTQtYTI4ZGUzNWIxNTVmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Anthony Russo (dir.), Ryan Gosling, Chris Evans",
        "imdb_rating": "6.5",
        "imdb_rating_count": "94830"
    },
    {
        "rank": "2",
        "rank_up_down": "+1",
        "title": "Nope",
        "full_title": "Nope (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMGIyNTI3NWItNTJkOS00MGYyLWE4NjgtZDhjMWQ4Y2JkZTU5XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jordan Peele (dir.), Daniel Kaluuya, Keke Palmer",
        "imdb_rating": "7.5",
        "imdb_rating_count": "19978"
    },
    {
        "rank": "3",
        "rank_up_down": "+109",
        "title": "Black Panther: Wakanda Forever",
        "full_title": "Black Panther: Wakanda Forever (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNjMxZmI4NzEtYWNjOS00M2MwLWE4YTctMjk1YWEzOTY1NjkwXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Ryan Coogler (dir.), Letitia Wright, Lupita Nyong'o",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "4",
        "rank_up_down": "-2",
        "title": "Thor: Love and Thunder",
        "full_title": "Thor: Love and Thunder (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDdlNDNkOTEzYTdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Taika Waititi (dir.), Chris Hemsworth, Natalie Portman",
        "imdb_rating": "6.8",
        "imdb_rating_count": "144591"
    },
    {
        "rank": "5",
        "rank_up_down": "-1",
        "title": "The Black Phone",
        "full_title": "The Black Phone (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOWVmNTBiYTUtZWQ3Yi00ZDlhLTgyYjUtNzBhZjM3YjRiNGRkXkEyXkFqcGdeQXVyNzYyOTM1ODI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Scott Derrickson (dir.), Mason Thames, Madeleine McGraw",
        "imdb_rating": "7.0",
        "imdb_rating_count": "67625"
    },
    {
        "rank": "6",
        "rank_up_down": "0",
        "title": "Where the Crawdads Sing",
        "full_title": "Where the Crawdads Sing (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMTJmNGJmYTgtYjAxNy00YmMzLTk2YTYtMGIzMmUwNDMyMTY1XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UY176_CR6,0,128,176_AL_.jpg",
        "crew": "Olivia Newman (dir.), Daisy Edgar-Jones, Taylor John Smith",
        "imdb_rating": "7.1",
        "imdb_rating_count": "7648"
    },
    {
        "rank": "7",
        "rank_up_down": "0",
        "title": "Top Gun: Maverick",
        "full_title": "Top Gun: Maverick (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOWQwOTA1ZDQtNzk3Yi00ZmVmLWFiZGYtNjdjNThiYjJhNzRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly",
        "imdb_rating": "8.6",
        "imdb_rating_count": "254476"
    },
    {
        "rank": "8",
        "rank_up_down": "0",
        "title": "Elvis",
        "full_title": "Elvis (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYzMzNTJjYmMtZTkxNS00MjI4LWI3YmQtOTQ4MDZjZDJlZjQyXkEyXkFqcGdeQXVyNjc0NzQzNTM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Baz Luhrmann (dir.), Tom Hanks, Austin Butler",
        "imdb_rating": "7.8",
        "imdb_rating_count": "54113"
    },
    {
        "rank": "9",
        "rank_up_down": "+255",
        "title": "Blonde",
        "full_title": "Blonde (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNDk2YTA1MGYtMGNjMi00YTJlLWI1YjItMjBjOGJlZGIwZmYzXkEyXkFqcGdeQXVyODA0MjgyNzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Andrew Dominik (dir.), Ana de Armas, Bobby Cannavale",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "10",
        "rank_up_down": "+50",
        "title": "Shamshera",
        "full_title": "Shamshera (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BODVlNWNmN2EtYWJlYy00ZTc5LThjMTItYTQ0ZTlmZDYwN2VjXkEyXkFqcGdeQXVyNTkzNDQ4ODc@._V1_UY176_CR0,0,128,176_AL_.jpg",
        "crew": "Karan Malhotra (dir.), Ranbir Kapoor, Sanjay Dutt",
        "imdb_rating": "7.4",
        "imdb_rating_count": "48020"
    },
    {
        "rank": "11",
        "rank_up_down": "+1",
        "title": "Everything Everywhere All at Once",
        "full_title": "Everything Everywhere All at Once (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Dan Kwan (dir.), Michelle Yeoh, Stephanie Hsu",
        "imdb_rating": "8.2",
        "imdb_rating_count": "164945"
    },
    {
        "rank": "12",
        "rank_up_down": "-2",
        "title": "Jurassic World Dominion",
        "full_title": "Jurassic World Dominion (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOTBjMjA4NmYtN2RjMi00YWZlLTliYTktOTIwMmNkYjYxYmE1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Colin Trevorrow (dir.), Chris Pratt, Bryce Dallas Howard",
        "imdb_rating": "5.7",
        "imdb_rating_count": "104876"
    },
    {
        "rank": "13",
        "rank_up_down": "-8",
        "title": "Persuasion",
        "full_title": "Persuasion (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZDg3MzdiYjAtZWQ0MC00MDY4LWE5ZWEtNjliNTE3ZDZjNTU3XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Carrie Cracknell (dir.), Richard E. Grant, Henry Golding",
        "imdb_rating": "5.6",
        "imdb_rating_count": "16818"
    },
    {
        "rank": "14",
        "rank_up_down": "+18",
        "title": "X",
        "full_title": "X (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMTJiMmE5YWItOWZjYS00YTg0LWE0MTYtMzg2ZTY4YjNkNDEzXkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UY176_CR6,0,128,176_AL_.jpg",
        "crew": "Ti West (dir.), Mia Goth, Jenna Ortega",
        "imdb_rating": "6.6",
        "imdb_rating_count": "55778"
    },
    {
        "rank": "15",
        "rank_up_down": "+647",
        "title": "Shazam! Fury of the Gods",
        "full_title": "Shazam! Fury of the Gods (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNTBmNjQ5MTUtMzMxMi00NTk1LWExYjEtMzNkZGE4MTFjNzlkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "David F. Sandberg (dir.), Grace Caroline Currey, Zachary Levi",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "16",
        "rank_up_down": "0",
        "title": "Bullet Train",
        "full_title": "Bullet Train (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMDU2ZmM2OTYtNzIxYy00NjM5LTliNGQtN2JmOWQzYTBmZWUzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "David Leitch (dir.), Brad Pitt, Sandra Bullock",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "17",
        "rank_up_down": "+26",
        "title": "DC League of Super-Pets",
        "full_title": "DC League of Super-Pets (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNjA5ZDBlMDMtZTM3Zi00MGEwLWJkZmMtMGEyOGRmMTA2NWQ3XkEyXkFqcGdeQXVyMTUzOTcyODA5._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jared Stern (dir.), Dwayne Johnson, Kevin Hart",
        "imdb_rating": "7.8",
        "imdb_rating_count": "10634"
    },
    {
        "rank": "18",
        "rank_up_down": "+1",
        "title": "Oppenheimer",
        "full_title": "Oppenheimer (2023)",
        "year": "2023",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMDI5ZTVmMmMtZjg1Ny00NzNkLWFkMDctZDlmMzQ4MDcyODZlXkEyXkFqcGdeQXVyMzM1NDY1MDE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Christopher Nolan (dir.), Jack Quaid, Florence Pugh",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "19",
        "rank_up_down": "-10",
        "title": "Dungeons & Dragons: Honor Among Thieves",
        "full_title": "Dungeons & Dragons: Honor Among Thieves (2023)",
        "year": "2023",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZDQ5NzJmZGItYjkxNS00MTVmLWJlODItMDViYzIxNDFmOTNlXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "John Francis Daley (dir.), Chris Pine, Michelle Rodriguez",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "20",
        "rank_up_down": "-7",
        "title": "Doctor Strange in the Multiverse of Madness",
        "full_title": "Doctor Strange in the Multiverse of Madness (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Sam Raimi (dir.), Benedict Cumberbatch, Elizabeth Olsen",
        "imdb_rating": "7.0",
        "imdb_rating_count": "335641"
    },
    {
        "rank": "21",
        "rank_up_down": "+45",
        "title": "John Wick: Chapter 4",
        "full_title": "John Wick: Chapter 4 (2023)",
        "year": "2023",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOTI1MDA5OTEtNWExMi00NGYwLThmMjUtMDhmNDQ4YTg1NzZlXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UY176_CR0,0,128,176_AL_.jpg",
        "crew": "Chad Stahelski (dir.), Keanu Reeves, Donnie Yen",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "22",
        "rank_up_down": "-5",
        "title": "Barbie",
        "full_title": "Barbie (2023)",
        "year": "2023",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNzliODE4NDQtYzEwNy00N2QyLTk2ZGQtZGZhNDU0NjVlZDMyXkEyXkFqcGdeQXVyMTU0Mjc4MTY4._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Greta Gerwig (dir.), Ryan Gosling, Margot Robbie",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "23",
        "rank_up_down": "-12",
        "title": "The Sea Beast",
        "full_title": "The Sea Beast (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BODkyYTRlMDItMDlhMC00MzkzLWI3NzQtOGVlMjdjYThlNDM3XkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Chris Williams (dir.), Karl Urban, Zaris-Angel Hator",
        "imdb_rating": "7.1",
        "imdb_rating_count": "23934"
    },
    {
        "rank": "24",
        "rank_up_down": "+40",
        "title": "Prey",
        "full_title": "Prey (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMDBlMDYxMDktOTUxMS00MjcxLWE2YjQtNjNhMjNmN2Y3ZDA1XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Dan Trachtenberg (dir.), Amber Midthunder, Dane DiLiegro",
        "imdb_rating": "6.6",
        "imdb_rating_count": "422"
    },
    {
        "rank": "25",
        "rank_up_down": "+842",
        "title": "Ant-Man and the Wasp: Quantumania",
        "full_title": "Ant-Man and the Wasp: Quantumania (2023)",
        "year": "2023",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNzg4MDYwZDktZDI2Yy00NmJhLTg2ZWUtZjIwNzQ2MTgxMDIyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Peyton Reed (dir.), Kathryn Newton, Jonathan Majors",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "26",
        "rank_up_down": "+80",
        "title": "Black Adam",
        "full_title": "Black Adam (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BN2ZmYTlhNmMtODQ0OS00YWNiLWI1MmMtNzkwYWMzOGM4YWQxXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jaume Collet-Serra (dir.), Dwayne Johnson, Sarah Shahi",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "27",
        "rank_up_down": "-9",
        "title": "Top Gun",
        "full_title": "Top Gun (1986)",
        "year": "1986",
        "img_url": "https://m.media-amazon.com/images/M/MV5BY2NlZjQ3ZTAtMzcxZC00MGZhLWFhNTQtN2M4NDBjYzIyOWNlXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Tony Scott (dir.), Tom Cruise, Tim Robbins",
        "imdb_rating": "6.9",
        "imdb_rating_count": "398316"
    },
    {
        "rank": "28",
        "rank_up_down": "-6",
        "title": "The Batman",
        "full_title": "The Batman (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Matt Reeves (dir.), Robert Pattinson, Zoë Kravitz",
        "imdb_rating": "7.9",
        "imdb_rating_count": "558204"
    },
    {
        "rank": "29",
        "rank_up_down": "-15",
        "title": "Minions: The Rise of Gru",
        "full_title": "Minions: The Rise of Gru (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZDQyODUwM2MtNzA0YS00ZjdmLTgzMjItZWRjN2YyYWE5ZTNjXkEyXkFqcGdeQXVyMTI2MzY1MjM1._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Kyle Balda (dir.), Steve Carell, Pierre Coffin",
        "imdb_rating": "6.9",
        "imdb_rating_count": "28157"
    },
    {
        "rank": "30",
        "rank_up_down": "-7",
        "title": "The Northman",
        "full_title": "The Northman (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMzVlMmY2NTctODgwOC00NDMzLWEzMWYtM2RiYmIyNTNhMTI0XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Robert Eggers (dir.), Alexander Skarsgård, Nicole Kidman",
        "imdb_rating": "7.2",
        "imdb_rating_count": "151251"
    },
    {
        "rank": "31",
        "rank_up_down": "+280",
        "title": "Not Okay",
        "full_title": "Not Okay (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYTM2ZjBiZTYtNGM0Zi00ZGY5LTgyNjItNzVjNDVlMmE5NmI2XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Quinn Shephard (dir.), Zoey Deutch, Mia Isaac",
        "imdb_rating": "6.1",
        "imdb_rating_count": "3305"
    },
    {
        "rank": "32",
        "rank_up_down": "-12",
        "title": "Spider-Man: No Way Home",
        "full_title": "Spider-Man: No Way Home (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jon Watts (dir.), Tom Holland, Zendaya",
        "imdb_rating": "8.3",
        "imdb_rating_count": "693642"
    },
    {
        "rank": "33",
        "rank_up_down": "-5",
        "title": "The Godfather",
        "full_title": "The Godfather (1972)",
        "year": "1972",
        "img_url": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,1,128,176_AL_.jpg",
        "crew": "Francis Ford Coppola (dir.), Marlon Brando, Al Pacino",
        "imdb_rating": "9.2",
        "imdb_rating_count": "1813362"
    },
    {
        "rank": "34",
        "rank_up_down": "-10",
        "title": "Sing 2",
        "full_title": "Sing 2 (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMWRiZGQ1NDMtODQ2OS00MDlhLWJkZGYtM2ZmNjlhZThjOWRmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Garth Jennings (dir.), Matthew McConaughey, Reese Witherspoon",
        "imdb_rating": "7.4",
        "imdb_rating_count": "59662"
    },
    {
        "rank": "35",
        "rank_up_down": "+381",
        "title": "Guardians of the Galaxy Vol. 3",
        "full_title": "Guardians of the Galaxy Vol. 3 (2023)",
        "year": "2023",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNmVhN2IyMTUtZTg3ZS00YWYxLTg3OTItMTFlNGM0MDYyNWI3XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "James Gunn (dir.), Chris Pratt, Zoe Saldana",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "36",
        "rank_up_down": "-9",
        "title": "House of Gucci",
        "full_title": "House of Gucci (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYzdlMTMyZWQtZWNmMC00MTJiLWIyMWMtM2ZlZDdlYzZhNTc0XkEyXkFqcGdeQXVyMTMzNDE5NDM2._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Ridley Scott (dir.), Lady Gaga, Adam Driver",
        "imdb_rating": "6.6",
        "imdb_rating_count": "118476"
    },
    {
        "rank": "37",
        "rank_up_down": "-7",
        "title": "Don't Worry Darling",
        "full_title": "Don't Worry Darling (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOTU1YjhhMDUtNzBhOS00MTc3LTlmZWEtZGIzYjZmZmZhNTU2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Olivia Wilde (dir.), Florence Pugh, Olivia Wilde",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "38",
        "rank_up_down": "+613",
        "title": "Samaritan",
        "full_title": "Samaritan (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BY2M2MjMxNjUtZWU2MS00NTIwLWE0ZDEtOTY3NzY5NGZmY2RmXkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Julius Avery (dir.), Sylvester Stallone, Pilou Asbæk",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "39",
        "rank_up_down": "+56",
        "title": "Goodfellas",
        "full_title": "Goodfellas (1990)",
        "year": "1990",
        "img_url": "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Martin Scorsese (dir.), Robert De Niro, Ray Liotta",
        "imdb_rating": "8.7",
        "imdb_rating_count": "1133885"
    },
    {
        "rank": "40",
        "rank_up_down": "+836",
        "title": "Purple Hearts",
        "full_title": "Purple Hearts (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNzI4ZTAwNzEtNTk5YS00ZWJmLWI1ODMtOTU4MTM5MzQ4OWM0XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UY176_CR24,0,128,176_AL_.jpg",
        "crew": "Elizabeth Allen Rosenbaum (dir.), Sofia Carson, Nicholas Galitzine",
        "imdb_rating": "7.2",
        "imdb_rating_count": "5384"
    },
    {
        "rank": "41",
        "rank_up_down": "-16",
        "title": "Last Night in Soho",
        "full_title": "Last Night in Soho (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZjgwZDIwY2MtNGZlNy00NGRlLWFmNTgtOTBkZThjMDUwMGJhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Edgar Wright (dir.), Thomasin McKenzie, Anya Taylor-Joy",
        "imdb_rating": "7.1",
        "imdb_rating_count": "120852"
    },
    {
        "rank": "42",
        "rank_up_down": "-3",
        "title": "The Lost City",
        "full_title": "The Lost City (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMmIwYzFhODAtY2I1YS00ZDdmLTkyYWQtZjI5NDIwMDc2MjEyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Aaron Nee (dir.), Sandra Bullock, Channing Tatum",
        "imdb_rating": "6.1",
        "imdb_rating_count": "85397"
    },
    {
        "rank": "43",
        "rank_up_down": "-9",
        "title": "Incantation",
        "full_title": "Incantation (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYjUxZGI1ODQtMDljMS00ZTUwLWI0NTMtYjc2YmUyZTM3YTdhXkEyXkFqcGdeQXVyNTM2NTY4NzU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Kevin Ko (dir.), Hsuan-yen Tsai, Ying-Hsuan Kao",
        "imdb_rating": "6.2",
        "imdb_rating_count": "7283"
    },
    {
        "rank": "44",
        "rank_up_down": "+13",
        "title": "Get Out",
        "full_title": "Get Out (2017)",
        "year": "2017",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jordan Peele (dir.), Daniel Kaluuya, Allison Williams",
        "imdb_rating": "7.7",
        "imdb_rating_count": "575133"
    },
    {
        "rank": "45",
        "rank_up_down": "3,876",
        "title": "The Whale",
        "full_title": "The Whale (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNTk0ZGE4MTAtYjhhMy00NjYyLTk2MjgtZTEzYzdkMWViNTMwXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UY176_CR53,0,128,176_AL_.jpg",
        "crew": "Darren Aronofsky (dir.), Brendan Fraser, Sadie Sink",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "46",
        "rank_up_down": "+119",
        "title": "Vengeance",
        "full_title": "Vengeance (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNDkyZGFjZDEtODdiZS00YmJiLWE2NTEtZGIxMTUzN2ZjZjA3XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "B.J. Novak (dir.), Isabella Amara, Nathaniel Augustson",
        "imdb_rating": "7.3",
        "imdb_rating_count": "861"
    },
    {
        "rank": "47",
        "rank_up_down": "+23",
        "title": "Rocketry: The Nambi Effect",
        "full_title": "Rocketry: The Nambi Effect (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNTk2MjUxMjEtZDU5OC00MzYxLTkwMWYtMGM5YWQ0MWMyN2I1XkEyXkFqcGdeQXVyMTE0MzY0NjE1._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Madhavan (dir.), Madhavan, Simran",
        "imdb_rating": "9.1",
        "imdb_rating_count": "23405"
    },
    {
        "rank": "48",
        "rank_up_down": "+14",
        "title": "Once Upon a Time... In Hollywood",
        "full_title": "Once Upon a Time... In Hollywood (2019)",
        "year": "2019",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Quentin Tarantino (dir.), Leonardo DiCaprio, Brad Pitt",
        "imdb_rating": "7.6",
        "imdb_rating_count": "706417"
    },
    {
        "rank": "49",
        "rank_up_down": "+237",
        "title": "Black Panther",
        "full_title": "Black Panther (2018)",
        "year": "2018",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Ryan Coogler (dir.), Chadwick Boseman, Michael B. Jordan",
        "imdb_rating": "7.3",
        "imdb_rating_count": "735847"
    },
    {
        "rank": "50",
        "rank_up_down": "-29",
        "title": "Lightyear",
        "full_title": "Lightyear (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYTg2Zjk0ZTctM2ZmMi00MDRmLWJjOGYtNWM0YjBmZTBjMjRkXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Angus MacLane (dir.), Chris Evans, Keke Palmer",
        "imdb_rating": "5.5",
        "imdb_rating_count": "56738"
    },
    {
        "rank": "51",
        "rank_up_down": "-14",
        "title": "Hustle",
        "full_title": "Hustle (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYjdhYTE3NjMtZjI3OC00NzVlLWFiNTUtNzQ3NDNiNTI3NDg4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jeremiah Zagar (dir.), Adam Sandler, Queen Latifah",
        "imdb_rating": "7.3",
        "imdb_rating_count": "94548"
    },
    {
        "rank": "52",
        "rank_up_down": "-26",
        "title": "Winnie-The-Pooh: Blood and Honey",
        "full_title": "Winnie-The-Pooh: Blood and Honey ( 26)",
        "year": " 26",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNTg2MDhhYzQtNDZjNi00MjRmLTg3NWYtMzg2ZGJkYmI2MmE0XkEyXkFqcGdeQXVyNjUxMDQ0MTg@._V1_UY176_CR0,0,128,176_AL_.jpg",
        "crew": "Rhys Frake-Waterfield (dir.), Natasha Tosini, Amber Doig-Thorne",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "53",
        "rank_up_down": "+25",
        "title": "Killers of the Flower Moon",
        "full_title": "Killers of the Flower Moon (2023)",
        "year": "2023",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZmMyMDc4NWMtZmUzNC00ZjczLWE1ZmYtYWQ3ZTk4ODBmYzE2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY176_CR69,0,128,176_AL_.jpg",
        "crew": "Martin Scorsese (dir.), Leonardo DiCaprio, Robert De Niro",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "54",
        "rank_up_down": "-18",
        "title": "The Man from Toronto",
        "full_title": "The Man from Toronto (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZDM2YjA2ZjAtMmZmMy00NDhjLWJjYWYtYjc4ZGY0YzUzOTMyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Patrick Hughes (dir.), Kevin Hart, Woody Harrelson",
        "imdb_rating": "5.8",
        "imdb_rating_count": "34954"
    },
    {
        "rank": "55",
        "rank_up_down": "+4",
        "title": "Paws of Fury: The Legend of Hank",
        "full_title": "Paws of Fury: The Legend of Hank (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNjJlNDA5ODQtZWJlNy00NWU2LTkyMWItZWY5NzZlMTlmMWFhXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Chris Bailey (dir.), Michael Cera, Samuel L. Jackson",
        "imdb_rating": "5.5",
        "imdb_rating_count": "1649"
    },
    {
        "rank": "56",
        "rank_up_down": "-4",
        "title": "365 Days",
        "full_title": "365 Days (2020)",
        "year": "2020",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMDdhYzNkOWQtYWNlNi00NDdjLWJlZDMtMjJjZDYyNjAxM2U1XkEyXkFqcGdeQXVyMTQyMTMwOTk0._V1_UY176_CR0,0,128,176_AL_.jpg",
        "crew": "Barbara Bialowas (dir.), Anna-Maria Sieklucka, Michele Morrone",
        "imdb_rating": "3.3",
        "imdb_rating_count": "85359"
    },
    {
        "rank": "57",
        "rank_up_down": "-12",
        "title": "Men",
        "full_title": "Men (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZGQ2ZDNiMjgtMTNhNS00MjUxLWFkYTMtYTI1OTE0MmQ2MmJkXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Alex Garland (dir.), Jessie Buckley, Rory Kinnear",
        "imdb_rating": "6.1",
        "imdb_rating_count": "23739"
    },
    {
        "rank": "58",
        "rank_up_down": "0",
        "title": "The Shawshank Redemption",
        "full_title": "The Shawshank Redemption (1994)",
        "year": "1994",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Frank Darabont (dir.), Tim Robbins, Morgan Freeman",
        "imdb_rating": "9.3",
        "imdb_rating_count": "2618695"
    },
    {
        "rank": "59",
        "rank_up_down": "+2",
        "title": "No Time to Die",
        "full_title": "No Time to Die (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Cary Joji Fukunaga (dir.), Daniel Craig, Ana de Armas",
        "imdb_rating": "7.3",
        "imdb_rating_count": "380067"
    },
    {
        "rank": "60",
        "rank_up_down": "1,432",
        "title": "Till",
        "full_title": "Till (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZjdlYzkxOTctNTk2ZC00NWE0LWI4NDEtMjA0Yzg1OTQ0YmJmXkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Chinonye Chukwu (dir.), Haley Bennett, Whoopi Goldberg",
        "imdb_rating": "",
        "imdb_rating_count": "0"
    },
    {
        "rank": "61",
        "rank_up_down": "-46",
        "title": "Zombies 3",
        "full_title": "Zombies 3 (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZDg4MjVhZDQtM2RiNC00NzZkLWI4MWMtMjkxNjMyZGM3ZmRmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY176_CR6,0,128,176_AL_.jpg",
        "crew": "Paul Hoen (dir.), Meg Donnelly, Milo Manheim",
        "imdb_rating": "5.3",
        "imdb_rating_count": "1625"
    },
    {
        "rank": "62",
        "rank_up_down": "-13",
        "title": "The Unbearable Weight of Massive Talent",
        "full_title": "The Unbearable Weight of Massive Talent (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNDM2ODNiMWItOWRkNS00ODE3LWE2OGYtNTZkMDJkOWI1ODMxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Tom Gormican (dir.), Nicolas Cage, Pedro Pascal",
        "imdb_rating": "7.1",
        "imdb_rating_count": "60589"
    },
    {
        "rank": "63",
        "rank_up_down": "-16",
        "title": "RRR",
        "full_title": "RRR (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BODUwNDNjYzctODUxNy00ZTA2LWIyYTEtMDc5Y2E5ZjBmNTMzXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY176_CR0,0,128,176_AL_.jpg",
        "crew": "S.S. Rajamouli (dir.), N.T. Rama Rao Jr., Ram Charan",
        "imdb_rating": "8.0",
        "imdb_rating_count": "89828"
    },
    {
        "rank": "64",
        "rank_up_down": "+15",
        "title": "Avengers: Endgame",
        "full_title": "Avengers: Endgame (2019)",
        "year": "2019",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Anthony Russo (dir.), Robert Downey Jr., Chris Evans",
        "imdb_rating": "8.4",
        "imdb_rating_count": "1082525"
    },
    {
        "rank": "65",
        "rank_up_down": "+962",
        "title": "Honor Society",
        "full_title": "Honor Society (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BODk0MjFlY2YtOGFmMi00OTVjLTkwMzctOTdlYzYzNTZkMmRmXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Oran Zegman (dir.), Angourie Rice, Gaten Matarazzo",
        "imdb_rating": "6.4",
        "imdb_rating_count": "1277"
    },
    {
        "rank": "66",
        "rank_up_down": "-10",
        "title": "The Bad Guys",
        "full_title": "The Bad Guys (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMDhkYmU0MzctMWEzNy00ODg1LWI3ZjAtMGZlZjkzNWVmMzVjXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Pierre Perifel (dir.), Sam Rockwell, Marc Maron",
        "imdb_rating": "6.8",
        "imdb_rating_count": "29203"
    },
    {
        "rank": "67",
        "rank_up_down": "+33",
        "title": "Titanic",
        "full_title": "Titanic (1997)",
        "year": "1997",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "James Cameron (dir.), Leonardo DiCaprio, Kate Winslet",
        "imdb_rating": "7.9",
        "imdb_rating_count": "1148541"
    },
    {
        "rank": "68",
        "rank_up_down": "-13",
        "title": "Uncharted",
        "full_title": "Uncharted (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Ruben Fleischer (dir.), Tom Holland, Mark Wahlberg",
        "imdb_rating": "6.4",
        "imdb_rating_count": "154761"
    },
    {
        "rank": "69",
        "rank_up_down": "-31",
        "title": "Spiderhead",
        "full_title": "Spiderhead (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNDVkZTc4OTktNTAyOC00MzQxLThiZjMtM2M3MTlmYzFjY2FkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Joseph Kosinski (dir.), Chris Hemsworth, Miles Teller",
        "imdb_rating": "5.4",
        "imdb_rating_count": "45519"
    },
    {
        "rank": "70",
        "rank_up_down": "-17",
        "title": "Fantastic Beasts: The Secrets of Dumbledore",
        "full_title": "Fantastic Beasts: The Secrets of Dumbledore (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZGQ1NjQyNDMtNzFlZS00ZGIzLTliMWUtNGJkMGMzNTBjNDg0XkEyXkFqcGdeQXVyMTE1NDI5MDQx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "David Yates (dir.), Eddie Redmayne, Jude Law",
        "imdb_rating": "6.2",
        "imdb_rating_count": "118445"
    },
    {
        "rank": "71",
        "rank_up_down": "+641",
        "title": "The Reef: Stalked",
        "full_title": "The Reef: Stalked (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMGVhODM3Y2EtNzJlNy00YzVjLTgwNjgtMjZkOWNlNDhhYWY4XkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Andrew Traucki (dir.), Teressa Liane, Ann Truong",
        "imdb_rating": "4.0",
        "imdb_rating_count": "1021"
    },
    {
        "rank": "72",
        "rank_up_down": "-26",
        "title": "Orphan: First Kill",
        "full_title": "Orphan: First Kill (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZjgwNDA3MmUtMTQ3Yy00ZDFmLTgwMTktNTBlMTQ3ZTI5MjYxXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "William Brent Bell (dir.), Isabelle Fuhrman, Julia Stiles",
        "imdb_rating": "6.2",
        "imdb_rating_count": "266"
    },
    {
        "rank": "73",
        "rank_up_down": "+12",
        "title": "Us",
        "full_title": "Us (2019)",
        "year": "2019",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZTliNWJhM2YtNDc1MC00YTk1LWE2MGYtZmE4M2Y5ODdlNzQzXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jordan Peele (dir.), Lupita Nyong'o, Winston Duke",
        "imdb_rating": "6.8",
        "imdb_rating_count": "282754"
    },
    {
        "rank": "74",
        "rank_up_down": "5,632",
        "title": "Paradise Highway",
        "full_title": "Paradise Highway (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZTRjYmVhM2MtNWE0Ny00OWEyLWI4ZGQtYmI4NDQyYzJkYWE1XkEyXkFqcGdeQXVyMTAxMTM4NzU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Anna Gutto (dir.), Morgan Freeman, Frank Grillo",
        "imdb_rating": "5.3",
        "imdb_rating_count": "649"
    },
    {
        "rank": "75",
        "rank_up_down": "-42",
        "title": "Girl in the Picture",
        "full_title": "Girl in the Picture (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZmNmM2ZmOWUtMThlMS00OTFiLWEyZjAtMjJmOWFjZDJlODg4XkEyXkFqcGdeQXVyMTQyOTAzNTU5._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Skye Borgman (dir.), Karen Parsley, Charles Engles",
        "imdb_rating": "7.2",
        "imdb_rating_count": "11943"
    },
    {
        "rank": "76",
        "rank_up_down": "-5",
        "title": "Blade Runner 2049",
        "full_title": "Blade Runner 2049 (2017)",
        "year": "2017",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Denis Villeneuve (dir.), Harrison Ford, Ryan Gosling",
        "imdb_rating": "8.0",
        "imdb_rating_count": "551353"
    },
    {
        "rank": "77",
        "rank_up_down": "-14",
        "title": "Ghostbusters: Afterlife",
        "full_title": "Ghostbusters: Afterlife (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMGY2NjUwODEtMGM5OS00MzhkLWEzYTUtYjkwMjFmNjhiN2FmXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jason Reitman (dir.), Carrie Coon, Paul Rudd",
        "imdb_rating": "7.1",
        "imdb_rating_count": "166547"
    },
    {
        "rank": "78",
        "rank_up_down": "-38",
        "title": "The Princess",
        "full_title": "The Princess (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOGYyZjhkYTgtYzNlNC00NWEwLWEwMmQtZWI5Y2Y4OTk5Y2YwXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Le-Van Kiet (dir.), Joey King, Olga Kurylenko",
        "imdb_rating": "5.5",
        "imdb_rating_count": "9232"
    },
    {
        "rank": "79",
        "rank_up_down": "+218",
        "title": "Emma.",
        "full_title": "Emma. (2020)",
        "year": "2020",
        "img_url": "https://m.media-amazon.com/images/M/MV5BOGRiODEzM2QtOTUyYi00MWRlLTg4MzMtZGI0YmUzNWUyMjQ0XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Autumn de Wilde (dir.), Anya Taylor-Joy, Johnny Flynn",
        "imdb_rating": "6.7",
        "imdb_rating_count": "51839"
    },
    {
        "rank": "80",
        "rank_up_down": "-12",
        "title": "Death on the Nile",
        "full_title": "Death on the Nile (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNjI4ZTQ1OTYtNTI0Yi00M2EyLThiNjMtMzk1MmZlOWMyMDQwXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Kenneth Branagh (dir.), Tom Bateman, Annette Bening",
        "imdb_rating": "6.3",
        "imdb_rating_count": "130205"
    },
    {
        "rank": "81",
        "rank_up_down": "-16",
        "title": "Dune",
        "full_title": "Dune (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Denis Villeneuve (dir.), Timothée Chalamet, Rebecca Ferguson",
        "imdb_rating": "8.0",
        "imdb_rating_count": "595087"
    },
    {
        "rank": "82",
        "rank_up_down": "-51",
        "title": "The Forgiven",
        "full_title": "The Forgiven (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMzM1NGJkMzMtOWQ1Ni00ZTM1LWI4ZmYtYzAzMjBmNTg4Y2ZlXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "John Michael McDonagh (dir.), Jessica Chastain, Matt Smith",
        "imdb_rating": "5.8",
        "imdb_rating_count": "1828"
    },
    {
        "rank": "83",
        "rank_up_down": "-33",
        "title": "Vikram",
        "full_title": "Vikram (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMmJhYTYxMGEtNjQ5NS00MWZiLWEwN2ItYjJmMWE2YTU1YWYxXkEyXkFqcGdeQXVyMTEzNzg0Mjkx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Lokesh Kanagaraj (dir.), Kamal Haasan, Vijay Sethupathi",
        "imdb_rating": "8.5",
        "imdb_rating_count": "39926"
    },
    {
        "rank": "84",
        "rank_up_down": "-30",
        "title": "Jurassic Park",
        "full_title": "Jurassic Park (1993)",
        "year": "1993",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Steven Spielberg (dir.), Sam Neill, Laura Dern",
        "imdb_rating": "8.2",
        "imdb_rating_count": "970291"
    },
    {
        "rank": "85",
        "rank_up_down": "+104",
        "title": "John Wick",
        "full_title": "John Wick (2014)",
        "year": "2014",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Chad Stahelski (dir.), Keanu Reeves, Michael Nyqvist",
        "imdb_rating": "7.4",
        "imdb_rating_count": "614674"
    },
    {
        "rank": "86",
        "rank_up_down": "+11",
        "title": "Orphan",
        "full_title": "Orphan (2009)",
        "year": "2009",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMTBjMjY0ODEtZGVkMy00MjUyLTlkMjAtNDBmNzVjOTk0NzQyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Jaume Collet-Serra (dir.), Vera Farmiga, Peter Sarsgaard",
        "imdb_rating": "7.0",
        "imdb_rating_count": "216527"
    },
    {
        "rank": "87",
        "rank_up_down": "-1",
        "title": "Eternals",
        "full_title": "Eternals (2021)",
        "year": "2021",
        "img_url": "https://m.media-amazon.com/images/M/MV5BY2Y1ODBhYTItYmJiZi00NjU2LWI2NjktNTcwM2U2NGQ2ZTNiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Chloé Zhao (dir.), Gemma Chan, Richard Madden",
        "imdb_rating": "6.3",
        "imdb_rating_count": "324053"
    },
    {
        "rank": "88",
        "rank_up_down": "-1",
        "title": "Love",
        "full_title": "Love (2015)",
        "year": "2015",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZGQxZTFlZDctZjcyMy00NzA1LWFkMDYtNzRmZTkwYTFhYTc3XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Gaspar Noé (dir.), Aomi Muyock, Karl Glusman",
        "imdb_rating": "6.0",
        "imdb_rating_count": "58115"
    },
    {
        "rank": "89",
        "rank_up_down": "-8",
        "title": "The Wolf of Wall Street",
        "full_title": "The Wolf of Wall Street (2013)",
        "year": "2013",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Martin Scorsese (dir.), Leonardo DiCaprio, Jonah Hill",
        "imdb_rating": "8.2",
        "imdb_rating_count": "1363958"
    },
    {
        "rank": "90",
        "rank_up_down": "-7",
        "title": "Midsommar",
        "full_title": "Midsommar (2019)",
        "year": "2019",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Ari Aster (dir.), Florence Pugh, Jack Reynor",
        "imdb_rating": "7.1",
        "imdb_rating_count": "299011"
    },
    {
        "rank": "91",
        "rank_up_down": "+25",
        "title": "Deep Water",
        "full_title": "Deep Water (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BNTE1M2NjNDgtYjQ2Ny00YTMzLWJiYWQtMTdmM2Q2YjA1MDg1XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Adrian Lyne (dir.), Ben Affleck, Ana de Armas",
        "imdb_rating": "5.4",
        "imdb_rating_count": "40845"
    },
    {
        "rank": "92",
        "rank_up_down": "-41",
        "title": "Thor: Ragnarok",
        "full_title": "Thor: Ragnarok (2017)",
        "year": "2017",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Taika Waititi (dir.), Chris Hemsworth, Tom Hiddleston",
        "imdb_rating": "7.9",
        "imdb_rating_count": "725481"
    },
    {
        "rank": "93",
        "rank_up_down": "+43",
        "title": "Heat",
        "full_title": "Heat (1995)",
        "year": "1995",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYjZjNTJlZGUtZTE1Ny00ZDc4LTgwYjUtMzk0NDgwYzZjYTk1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,1,128,176_AL_.jpg",
        "crew": "Michael Mann (dir.), Al Pacino, Robert De Niro",
        "imdb_rating": "8.3",
        "imdb_rating_count": "642066"
    },
    {
        "rank": "94",
        "rank_up_down": "+56",
        "title": "Jug Jugg Jeeyo",
        "full_title": "Jug Jugg Jeeyo (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMTg5YjlkZmItZWZjOC00ZWQ5LTk2MjctYmI2ZGYzODY0N2ZmXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY176_CR0,0,128,176_AL_.jpg",
        "crew": "Raj Mehta (dir.), Varun Dhawan, Anil Kapoor",
        "imdb_rating": "7.0",
        "imdb_rating_count": "33594"
    },
    {
        "rank": "95",
        "rank_up_down": "-60",
        "title": "Bodies Bodies Bodies",
        "full_title": "Bodies Bodies Bodies (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYTA2ODg5ZjgtOTU2My00MzFkLWI0NzMtZmQ5MmRhMWU1NzhlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Halina Reijn (dir.), Amandla Stenberg, Maria Bakalova",
        "imdb_rating": "5.1",
        "imdb_rating_count": "376"
    },
    {
        "rank": "96",
        "rank_up_down": "-12",
        "title": "Interstellar",
        "full_title": "Interstellar (2014)",
        "year": "2014",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway",
        "imdb_rating": "8.6",
        "imdb_rating_count": "1760995"
    },
    {
        "rank": "97",
        "rank_up_down": "-24",
        "title": "Crimes of the Future",
        "full_title": "Crimes of the Future (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BZDdjODNkMmYtYjMwNS00NTQzLThlYjUtODY2ZjdjNTNlY2JiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "David Cronenberg (dir.), Viggo Mortensen, Léa Seydoux",
        "imdb_rating": "5.9",
        "imdb_rating_count": "15487"
    },
    {
        "rank": "98",
        "rank_up_down": "+81",
        "title": "Deadpool",
        "full_title": "Deadpool (2016)",
        "year": "2016",
        "img_url": "https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Tim Miller (dir.), Ryan Reynolds, Morena Baccarin",
        "imdb_rating": "8.0",
        "imdb_rating_count": "1011274"
    },
    {
        "rank": "99",
        "rank_up_down": "-22",
        "title": "The Dark Knight",
        "full_title": "The Dark Knight (2008)",
        "year": "2008",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Christopher Nolan (dir.), Christian Bale, Heath Ledger",
        "imdb_rating": "9.0",
        "imdb_rating_count": "2590629"
    },
    {
        "rank": "100",
        "rank_up_down": "+59",
        "title": "Prizefighter: The Life of Jem Belcher",
        "full_title": "Prizefighter: The Life of Jem Belcher (2022)",
        "year": "2022",
        "img_url": "https://m.media-amazon.com/images/M/MV5BMmE2OWM4YTAtNDkzNS00YTUyLWJjZjgtYmRhZDhlZmMxMGNiXkEyXkFqcGdeQXVyMjgxOTM1MDU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        "crew": "Daniel Graham (dir.), Matt Hookings, Ray Winstone",
        "imdb_rating": "5.4",
        "imdb_rating_count": "715"
    }
]]

movies.each do |movie|
  Movie.create(movie)
end



# const MOVIES_LIST = [
#   { id: 1, title: "Thor: Love and Thunder", synopsis: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.", img_url: "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDdlNDNkOTEzYTdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg", trailer_url: "https://imdb-video.media-imdb.com/vi1613808153/1434659607842-pgv4ql-1656941657492.mp4?Expires=1659101898&Signature=FcQu0v3H26gLEPedswQcuvNpfdoXvWLAODrmY~sPVrD9WlNLdwnd12ZH7a-768qZq-fHgG6a5VDtNLvOXCb27nyZ~7XjkwvCvo9qJjNmPEUL-nf9ifAQDIrTsSxKDzeSBZB~iDvT1AHW7oafBSoXwOOI3C9CL4VM6AjM4J1Z7on2fgxQ-xvXqwWEqbtzq2j~egmNNjFu8XEc0k~c~ycA4uvgNhubwUgxP6CQ3uy3hhgh5OTfCFWovJMcvivCJTeIhd~pJM702Zb8e9x1CIyJWp6uM2e0qoHTidssnV33CgiEMY4opgHTLAdrdREl4i102DHrLmbyV070E11GUFK6vA__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" },
#   { id: 2, title: "The Gray Man", synopsis: "When the CIA's most skilled operative-whose true identity is known to none-accidentally uncovers dark agency secrets, a psychopathic former colleague puts a bounty on his head, setting off a global manhunt by international assassins.", img_url: "https://m.media-amazon.com/images/M/MV5BOWY4MmFiY2QtMzE1YS00NTg1LWIwOTQtYTI4ZGUzNWIxNTVmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg", trailer_url: "https://imdb-video.media-imdb.com/vi941736473/1434659607842-pgv4ql-1657910195912.mp4?Expires=1659092769&Signature=DUz00QQcQWj4OHvxAxXBc75lnMV6X5dsbdiuOLod-VHW0RqAVi~AyDGaf4xoJDfQIU3yCSHYsMGc~xdzGXP9-gSdHiVMTeKfKJca0vr0uozqDBFad7tBz9lxo4rPegOpydpuAr-8fb-qsZ5hbYerVD2AsoI5gOO2-dTGW9FlysHudLqKEiRQHael0DNe-1TL1L72OsOPAK3YciGHU7f2BP7ptO154BEUgIB4xcMnqLlPP5gbaziYSyYnKPXeO~AckA7neYk7ZUNMmjIf~vWMgDe97dA1vzfjfXJ1ZtnozR8rYqwYMfl6m~vtfqfdX9DjGwNeTSxEuZAS4H8uaSsC2Q__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" },
#   { id: 3, title: "Jurassic World: Dominion", synopsis: "Four years after the destruction of Isla Nublar, dinosaurs now live--and hunt--alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history's most fearsome creatures in a new Era.", img_url: "https://m.media-amazon.com/images/M/MV5BOTBjMjA4NmYtN2RjMi00YWZlLTliYTktOTIwMmNkYjYxYmE1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg", trailer_url: "https://imdb-video.media-imdb.com/vi764854809/1434659607842-pgv4ql-1651159417077.mp4?Expires=1659092188&Signature=aJaWD86BOcGFlCjAebRHx4kjZuneJaCs6BcFUdjG3T~WhkbT--GIhHULjv2wIoPzTr6HdeGybBiYSwRjnN5-DrJ0wt4snHeat-i5V3tB6c7IvngVOhocN2neo48zptHOiBmwqicY2FFx3MfnOtJOaMVoI70NL1yWaD79Urcq4Ouh8SoClPP0FRCPXn8WxGrBhR2kH8e6PrK9dnlgC3fvX-HhNn9G68MTrLzJF22yjbzbHAdhe3zTW5qZDa-jKVEr1Ddwq2VkVcD9FfK5BilKMQvT2yV~0GNAcxUcMW~BdoVIWQ0A-92fkb~j9QxkZszB0VZwmPbFxfXAwD03FTcALA__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" },
#   { id: 4, title: "The Northman", synopsis: "From visionary director Robert Eggers comes The Northman, an action-filled epic that follows a young Viking prince on his quest to avenge his father's murder.", img_url: "https://m.media-amazon.com/images/M/MV5BMzVlMmY2NTctODgwOC00NDMzLWEzMWYtM2RiYmIyNTNhMTI0XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_.jpg", trailer_url: "https://imdb-video.media-imdb.com/vi2628633113/1434659607842-pgv4ql-1650564160409.mp4?Expires=1659092861&Signature=nW64fpKc-L52TBMhRtzLjnlbAVGbJeympVXUXA62RBVfPJ5mMOulBjL7oNZtskycJ5lzH0geauKuhg3XfCVxVgSyC8MBQfwkwBMYEft29btOQpJBR6d8Exk7U3lroGrbYn5c6nwmkmu1OlRCVqkk6RKlWGph8a6oDB9WYP106FA-vh6TIBDO10d~KDqc7j07ZveiwtoWBdbqFQbI7LliWGdaTuis4npDREvjgGyr-We-AQqmEHtI2SsIXieYwTtPfDfdbqwmzsE~ByuFzddP5gSxW72x4dHw-O~~gbx4zPVIJY5kGssIK7DmN1iVThU0paM6atoV763Jwt-On94nVQ__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" },
#   { id: 5, title: "Morbius", synopsis: "Biochemist Michael Morbius tries to cure himself of a rare blood disease, but he inadvertently infects himself with a form of vampirism instead.", img_url: "https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/title-key-art/morbius_onesheet_1400x2100_he.jpg?itok=-jQVkWIe", trailer_url: "https://imdb-video.media-imdb.com/vi862765849/1434659607842-pgv4ql-1646057736250.mp4?Expires=1659092921&Signature=SaHz4LqIiHktHidZy8ufCGDJVjA0lAUMncm2Tr8Rfd0~V-mBQC-fjLf0zgWfQGtUN0r~1x1IUsURLxLELIBAlnWeW8wIP6rfg8I2iyGS6ws8KDKwv9kPk7xMoYi41vbk3Keo0XxKS0Zeiqje4ZQ5TqfNEsdYWORPtTuawwy8C4GeCgz4Rkz8s4YiQNraJDxsWNz50DKTk2FLSHoG12ctyAiEW6mMYs8Kmo0y4rFG6FY-D0T3rscQMk73ygVTeiuyHD0qKCZ26eqoIMVhDoDFyxiXTNzMfDCVnpBx7bglgMnEz3IjNXtQ~lhNfjEImB8YdhiBklPqJDN3qVMdUiS7qg__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" },
#   { id: 6, title: "Uncharted", synopsis: "Street-smart Nathan Drake is recruited by seasoned treasure hunter Victor 'Sully' Sullivan to recover a fortune amassed by Ferdinand Magellan, and lost 500 years ago by the House of Moncada.", img_url: "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_.jpg", trailer_url: "https://imdb-video.media-imdb.com/vi420201241/1434659607842-pgv4ql-1644274969357.mp4?Expires=1659092963&Signature=TZHKB9-6IVqd9-Mv78deH8Hnl~FyHDcbHw-FSz9JxMPNUT8touLyusbW3Jjw2LSiDbtngCDc-h49f47aptV3WFYVG5noSbe-6yCk8ohOzfTdjwEVUCd2kuKYRDThoSyvGl6lZzSOFWAigFg4PWFARagbt4gWw1OLuM58uqT3tcmbaEFfhwZDX7SPnxxXRsjM8SB31blpsv~nlZtNyrAryQHgFEu12iSAIP4eUCYE~V7EZLLCrNkMCPPQfps7H81XJlsxldxd0QzgtF7cEqJLxIyMA4GwtRnskwicvz2Ru23CyBibhwmLaXVitT3GyTRPpgZStpiMQAzRFXWQ8jOYAQ__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" },
#   { id: 7, title: "Dune", synopsis: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.", img_url: "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg", trailer_url: "https://imdb-video.media-imdb.com/vi3967205401/1434659607842-pgv4ql-1626959425069.mp4?Expires=1659093007&Signature=lnXZWCOzx3oWEKlyif~PxQAc3L1iTVbpWT-EZH-qg-Oblxh8j3ydRFeSXT0V8FJcvO0GPaMpgYd1YwwLWkq5efTIYgrXTy8QYtNoQo3-7u-iO~8s7z1aj99qvhj2aU-buqpNkjqmjp1ScnoniZyPmUnYZ~DW1bCCrcRfLNYEn8Pj3zxBo2Nlx8uuGhNLS01Eu9xSmK0fKqKPwPhVzTMWyw-jiNbjhvtLHh8DDmZgIDK6si8Rtf3vHj4DguiCyL-c~2EVOqpB3vSVi~by4xQ-UC49kXM6n5Ap1E~gks7S-gQqIYzx1yw~KR96pGnq-JeS6Q1CL-r3F8EuOFVHw~GvgQ__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" },
#   { id: 7, title: "The Lion King", synopsis: "After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.", img_url: "https://m.media-amazon.com/images/M/MV5BMjIwMjE1Nzc4NV5BMl5BanBnXkFtZTgwNDg4OTA1NzM@._V1_.jpg", trailer_url: "https://imdb-video.media-imdb.com/vi3509369881/1434659607842-pgv4ql-1561659105801.mp4?Expires=1659102329&Signature=txOCIPVCj6A~EVzuJwtCTAk9v7LimweZduAHdbCuU-hbPVD8u8BUW0qgdaiMHcBO0yGBTWL6SxF6e00~OeTTd3-Saj6YxRAl-fkWja5nZc7Z3HLl67CBqShNS2-3oO5CLU5vzjyxXx8njyzarObAxbQ1RfAMGM1n5EQFaKxIAGTAk51Bxkl83wNjMRnK09hWwjV0KBfAln5Et6P8M3si-4207iX0Qy~xMVw5Qfo2adnGjRRO0x6eUIDtYBCJpbx0nG-91k8mlujLocooQud39qT9QdRLHU1E~agqHP66IwcmfMRa1lpswCovVpU3VhpSg6muP8smOImyA1pf-sJspw__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" }
# ]
